# Generated by Django 5.2.8 on 2025-11-17 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя актера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя режиссера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directors/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='topfive',
            name='movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posters/', verbose_name='Постер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='app.actor', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.director', verbose_name='Режиссер'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
        migrations.DeleteModel(
            name='TopFive',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
