# Generated by Django 5.2.8 on 2025-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный отзыв'),
        ),
    ]
