# Generated by Django 5.2.8 on 2025-12-01 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
